# 20장. 파이토치 텐서

<table align="left"><tr><td>
<a href="https://colab.research.google.com/github/rickiepark/ml-with-python-cookbook-2nd/blob/main/ch20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="코랩에서 실행하기"/></a>
</td></tr></table>

In [1]:
import numpy as np
import torch

print('numpy', np.__version__)
print('torch', torch.__version__)

numpy 1.26.4
torch 2.5.1+cu121


## 20.1 텐서 만들기

In [2]:
# 라이브러리를 임포트합니다.
import torch

# 하나의 행으로 벡터를 만듭니다.
tensor_row = torch.tensor([1, 2, 3])

# 하나의 열로 벡터를 만듭니다.
tensor_column = torch.tensor(
    [
        [1],
        [2],
        [3]
    ]
)

## 20.2 넘파이로 텐서 만들기

In [3]:
# 라이브러리를 임포트합니다.
import numpy as np
import torch

# 넘파이 배열을 만듭니다.
vector_row = np.array([1, 2, 3])

# 넘파이 배열로부터 텐서를 만듭니다.
tensor_row = torch.from_numpy(vector_row)

## 20.3 희소 텐서 만들기

In [4]:
# 라이브러리를 임포트합니다.
import torch

# 텐서를 만듭니다.
tensor = torch.tensor(
[
[0, 0],
[0, 1],
[3, 0]
]
)

# 일반 텐서로부터 희소 텐서를 만듭니다.
sparse_tensor = tensor.to_sparse()

In [5]:
print(type(tensor))
print(type(sparse_tensor))

<class 'torch.Tensor'>
<class 'torch.Tensor'>


## 20.4 텐서 원소 선택하기

In [6]:
# 라이브러리를 임포트합니다.
import torch

# 벡터 텐서를 만듭니다.
vector = torch.tensor([1, 2, 3, 4, 5, 6])

# 행렬 텐서를 만듭니다.
matrix = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

# 벡터의 세 번째 원소를 선택합니다.
vector[2]

tensor(3)

In [7]:
# 두 번째 행, 두 번째 열을 선택합니다.
matrix[1,1]

tensor(5)

In [8]:
# 벡터의 모든 원소를 선택합니다.
vector[:]

tensor([1, 2, 3, 4, 5, 6])

In [9]:
# 세 번째 원소를 포함해 모든 원소를 선택합니다.
vector[:3]

tensor([1, 2, 3])

In [10]:
# 세 번째 이후의 모든 원소를 선택합니다.
vector[3:]

tensor([4, 5, 6])

In [11]:
# 마지막 원소를 선택합니다.
vector[-1]

tensor(6)

In [12]:
# 처음 두 개 행의 모든 열을 선택합니다.
matrix[:2,:]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# 모든 행의 두 번째 열을 선택니다.
matrix[:,1:2]

tensor([[2],
        [5],
        [8]])

In [14]:
# 벡터를 뒤집습니다.
vector[::-1]

ValueError: step must be greater than zero

In [15]:
vector.flip(dims=(-1,))

tensor([6, 5, 4, 3, 2, 1])

## 20.5 텐서 구조 파악하기

In [16]:
# 라이브러리를 임포트합니다.
import torch

# 텐서를 만듭니다.
tensor = torch.tensor([[1,2,3], [1,2,3]])

# 텐서의 크기를 확인합니다.
tensor.shape

torch.Size([2, 3])

In [17]:
# 텐서 안에 있는 항목의 데이터 타입을 확인합니다.
tensor.dtype

torch.int64

In [18]:
# 텐서의 레이아웃을 확인합니다.
tensor.layout

torch.strided

In [19]:
# 텐서가 사용하는 장치를 확인합니다.
tensor.device

device(type='cpu')

## 20.6 원소에 연산 적용하기

In [20]:
# 라이브러리를 임포트합니다.
import torch

# 텐서를 만듭니다.
tensor = torch.tensor([1, 2, 3])

# 텐서에 있는 모든 원소에 산술 연산을 브로드캐스팅합니다.
tensor * 100

tensor([100, 200, 300])

## 20.7 최댓값과 최솟값 찾기

In [21]:
# 라이브러리를 임포트합니다.
import torch

# 텐서를 만듭니다.
torch.tensor([1,2,3])

# 최댓값을 찾습니다.
tensor.max()

tensor(3)

In [22]:
# 최솟값을 찾습니다.
tensor.min()

tensor(1)

In [23]:
# 다차원 텐서를 만듭니다.
tensor = torch.tensor([[1,2,3],[1,2,5]])

# 가장 큰 값을 찾습니다.
tensor.max()

tensor(5)

## 20.8 텐서 크기 바꾸기

In [24]:
# Load library
import torch

# Create 4x3 tensor
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9],
                       [10, 11, 12]])

# Reshape tensor into 2x6 tensor
tensor.reshape(2, 6)

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

## 20.9 텐서 전치하기

In [25]:
# 라이브러리를 임포트합니다.
import torch

# 2차원 텐서를 만듭니다.
tensor = torch.tensor([[[1,2,3]]])

# 텐서를 전치합니다.
tensor.mT

tensor([[[1],
         [2],
         [3]]])

In [26]:
tensor.permute(*torch.arange(tensor.ndim - 1, -1, -1))

tensor([[[1]],

        [[2]],

        [[3]]])

## 20.10 텐서 펼치기

In [27]:
# 라이브러리를 임포트합니다.
import torch

# 텐서를 만듭니다.
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

# 텐서를 펼칩니다.
tensor.flatten()

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 20.11 점곱을 계산하기

In [28]:
# 라이브러리를 임포트합니다.
import torch

# 텐서를 만듭니다.
tensor_1 = torch.tensor([1, 2, 3])

# 또 다른 텐서를 만듭니다.
tensor_2 = torch.tensor([4, 5, 6])

# 두 텐서의 점곱을 계산합니다.
tensor_1.dot(tensor_2)

tensor(32)

## 20.12 텐서 곱셈

In [29]:
# 라이브러리를 임포트합니다.
import torch

# 텐서를 만듭니다.
tensor_1 = torch.tensor([1, 2, 3])

# 또 다른 텐서를 만듭니다.
tensor_2 = torch.tensor([4, 5, 6])

# 두 텐서를 곱합니다.
tensor_1 * tensor_2

tensor([ 4, 10, 18])

In [30]:
tensor_1+tensor_2

tensor([5, 7, 9])

In [31]:
tensor_1-tensor_2

tensor([-3, -3, -3])

In [32]:
tensor_1/tensor_2

tensor([0.2500, 0.4000, 0.5000])